#!/bin/sh
#
# luafcgid for FreeBSD rc.d usage (c) 2009 STPeters
#
# PROVIDE: luafcgid
# REQUIRE: DAEMON
# KEYWORD: shutdown
#
# Add the following line to /etc/rc.conf to enable luafcgid:
#
# luafcgid_enable="YES"
# luafcgid_conf="/usr/local/etc/luafcgid.lua"
# luafcgid_user="www"

. /etc/rc.subr

name="luafcgid"
rcvar=`set_rcvar`
load_rc_config $name

: ${luafcgid_enable="NO"}
: ${luafcgid_conf="/usr/local/etc/luafcgid.lua"}
: ${luafcgid_user="www"}
: ${luafcgid_group="www"}

pidfile="/var/run/${name}.pid"
command="/usr/local/bin/luafcgid"
command_args="${luafcgid_conf}"

start_postcmd="luafcgid_poststart"
stop_postcmd="luafcgid_poststop"

luafcgid_poststart()
{
	echo `pgrep -P 1 -U ${luafcgid_user} -n -f ${command}` >$pidfile
}

luafcgid_poststop()
{
    rm -f $pidfile
}

run_rc_command "${1}"